//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CORREO
    {
        public int COR_ID { get; set; }
        public int PER_ID { get; set; }
        public string COR_DEFINICION { get; set; }
        public bool COR_ESTADO { get; set; }
    
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
    }
}
