//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ESTUDIANTE()
        {
            this.TBL_HIS_ESTUDIANTE_REGISTRO = new HashSet<TBL_HIS_ESTUDIANTE_REGISTRO>();
        }
    
        public int EST_ID { get; set; }
        public int PER_ID { get; set; }
        public int CUA_ID { get; set; }
        public string EST_CARNET { get; set; }
        public bool EST_ESTADO { get; set; }
    
        public virtual TBL_CUARTO TBL_CUARTO { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HIS_ESTUDIANTE_REGISTRO> TBL_HIS_ESTUDIANTE_REGISTRO { get; set; }
    }
}
