//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_HIS_ROL_ASEO
    {
        public int HIS_ROL_ASE_ID { get; set; }
        public int ROL_ASE_ID { get; set; }
        public int USU_ID { get; set; }
        public bool HIS_ROL_ASE_CUMPLE { get; set; }
        public System.DateTime HIS_ROL_ASE_FECHA { get; set; }
        public string HIS_ROL_ASE_DESCRIPCION { get; set; }
        public bool HIS_ROL_ASE_ESTADO { get; set; }
    
        public virtual TBL_ROL_ASEO TBL_ROL_ASEO { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
    }
}
