//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ESTUDIANTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_ESTUDIANTE()
        {
            this.TBL_HIS_ESTUDIANTE_CUARTO = new HashSet<TBL_HIS_ESTUDIANTE_CUARTO>();
            this.TBL_ROL_ASEO = new HashSet<TBL_ROL_ASEO>();
        }
    
        public int EST_ID { get; set; }
        public int CAR_ID { get; set; }
        public string EST_CARNET { get; set; }
        public System.DateTime EST_FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> EST_FECHA_FINAL { get; set; }
        public bool EST_ESTADO { get; set; }
    
        public virtual TBL_CARRERA TBL_CARRERA { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_HIS_ESTUDIANTE_CUARTO> TBL_HIS_ESTUDIANTE_CUARTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_ROL_ASEO> TBL_ROL_ASEO { get; set; }
    }
}
