//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIPO_AREA_RESPONSABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TIPO_AREA_RESPONSABLE()
        {
            this.TBL_RESPONSABLE = new HashSet<TBL_RESPONSABLE>();
        }
    
        public int TIP_ARE__RES_ID { get; set; }
        public string TIP_ARE_RES_DESCRIPCION { get; set; }
        public Nullable<bool> TIP_ARE_RES_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_RESPONSABLE> TBL_RESPONSABLE { get; set; }
    }
}
