//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PER_RELACION
    {
        public int PER_REL_ID { get; set; }
        public int TIP_PER_REL_ID { get; set; }
        public int PER_ORIGEN { get; set; }
        public int PER_DESTINO { get; set; }
        public System.DateTime PER_REL_FECHA_INICIAL { get; set; }
        public Nullable<System.DateTime> PER_REL_FECHA_FINAL { get; set; }
        public bool PER_REL_ESTADO { get; set; }
    
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA1 { get; set; }
        public virtual TBL_TIP_PER_RELACION TBL_TIP_PER_RELACION { get; set; }
    }
}
