//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_TIP_PER_RELACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_TIP_PER_RELACION()
        {
            this.TBL_PER_RELACION = new HashSet<TBL_PER_RELACION>();
        }
    
        public int TIP_PER_REL_ID { get; set; }
        public string TIP_PER_REL_DESCRIPCION { get; set; }
        public bool TIP_PER_REL_ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PER_RELACION> TBL_PER_RELACION { get; set; }
    }
}
